### ISSUE TITLE
How to call high-level methods?

### ISSUE THREAD

**Issue by munknex** [Arman92/go-tdlib#12]
Is it possible to call [high-level methods](https://core.telegram.org/methods)?

Like [contacts.getStatuses](https://core.telegram.org/method/contacts.getStatuses).

**Comment by munknex** [comment]
@Arman92 As far as I can see, code is generated only for [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) and not for [telegram_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/telegram_api.tl).

Is there any workaround to call a method from telegram_api?

**Comment by Arman92** [comment]
As far as I know, you can only call methods from tdlib api, not the legacy telegram api (i.e. mtproto protocol).

Why would you want to use the legacy methods? Telegram Tdlib has a complete set of methods for every use case.

**Comment by zelenin** [comment]
all wrong.
tdlib is high-level wrapper over low-level mtproto.
So mtproto is not legacy.

**Comment by Arman92** [comment]
> all wrong.
> tdlib is high-level wrapper over low-level mtproto.
> So mtproto is not legacy.

Ok, I misunderstood. but I don't think you can call low level mtproto methods over tdlib.

**Comment by zelenin** [comment]
> Ok, I misunderstood. but I don't think you can call low level mtproto methods over tdlib.

sure

**Comment by munknex** [comment]
@Arman92, @zelenin Please take a look at tdlib's `GetContactsStatusesQuery` [class](https://github.com/tdlib/td/blob/101aa73f132d5124d8da45bae11a29c423420072/td/telegram/ContactsManager.cpp#L440). It is used to get statuses by tdlib's ContactsManager using `contacts.getStatuses` method from `telegram_api.tl`.

tdlib automatically generate code from **both** `td_api.tl` and `telegram_api.tl`. Generated code can be found in your `./td/generate/auto/td/telegram/`.

So I think it should be possible to use this api too. Any thoughts?

**Comment by zelenin** [comment]
> So I think it should be possible to use this api too. 

Why do you think so?

**Comment by Arman92** [comment]
Tdlib json bindings library offers only the methods it declares in td_api.tl.

I'm closing this issue, if you think otherwise please do share with us.
