### ISSUE TITLE
macOS build fails: missing file tdjson_export.h

### ISSUE THREAD

**Issue by crackhd** [Arman92/go-tdlib#17]
I have cloned and built the tdlib with commands exactly from Readme

```
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . -- -j5

make install
```

On macOS Mojave, i am unable to build the Go example (from Readme) itself because of error:

```
go build -o app/bin/run_backend
# github.com/Arman92/go-tdlib
../../go/src/github.com/Arman92/go-tdlib/tdlib.go:10:10: fatal error: 'td/telegram/td_json_client.h' file not found
#include <td/telegram/td_json_client.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build] Error 2
```

I tried empty (default) GOPATH or appending path to `td` clone to it.

**To fix the error, create a symlink or copy "td/td" folder to `/usr/local/include`:**

```
$ ls -l /usr/local/include/td/.
total 0
drwxr-xr-x   33 travis  staff  1056 May 14 04:21 generate
drwxr-xr-x   35 travis  staff  1120 May 14 04:21 mtproto
drwxr-xr-x  206 travis  staff  6592 May 14 04:21 telegram
drwxr-xr-x    9 travis  staff   288 May 14 04:21 tl
```

**After this, error changed to missing file `tdjson_export.h`, and there is no such file anywhere**.

**Comment by crackhd** [comment]
To fix this error, i've tried to run `brew install openssl` and rebuild tdlib with this config (taken from #3):

`cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/lib ..`

but it did not resolve the problem.

```
go build -o app/bin/run_backend
# github.com/Arman92/go-tdlib
In file included from ../../go/src/github.com/Arman92/go-tdlib/tdlib.go:10:
/usr/local/include/td/telegram/td_json_client.h:50:10: fatal error: 'td/telegram/tdjson_export.h' file not found
#include "td/telegram/tdjson_export.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build] Error 2```

**Comment by Arman92** [comment]
It's not a go-tdlib issue. Have you looked at tdlib [Install Instructions](https://github.com/tdlib/td#installing-dependencies)?

Seems it's caused by a missing dependency, check out this [issue](https://github.com/tdlib/td/issues/276).

It's not a good idea, but anyway if you couldn't figure it out, here is what I found in the tdjson_export.h:
```c
#ifndef TDJSON_EXPORT_H
#define TDJSON_EXPORT_H

#ifdef TDJSON_STATIC_DEFINE
#  define TDJSON_EXPORT
#  define TDJSON_NO_EXPORT
#else
#  ifndef TDJSON_EXPORT
#    ifdef tdjson_EXPORTS
        /* We are building this library */
#      define TDJSON_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define TDJSON_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef TDJSON_NO_EXPORT
#    define TDJSON_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef TDJSON_DEPRECATED
#  define TDJSON_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef TDJSON_DEPRECATED_EXPORT
#  define TDJSON_DEPRECATED_EXPORT TDJSON_EXPORT TDJSON_DEPRECATED
#endif

#ifndef TDJSON_DEPRECATED_NO_EXPORT
#  define TDJSON_DEPRECATED_NO_EXPORT TDJSON_NO_EXPORT TDJSON_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TDJSON_NO_DEPRECATED
#    define TDJSON_NO_DEPRECATED
#  endif
#endif

#endif
```

**Comment by Arman92** [comment]
Also please take a look at this tool: [https://tdlib.github.io/td/build.html](https://tdlib.github.io/td/build.html)

**Comment by crackhd** [comment]
Thank you very much.
Dependencies was the problem.
However, this is the issue of tdlib, since normally configure script/cmake could be reporting about missing dependencies, but its not.

**Comment by crackhd** [comment]
Thank you, going to sort this out soon.
