### ISSUE TITLE
"pinChatMessage": Not enough rights to pin a message

### ISSUE THREAD

**Issue by leonmak** [Arman92/go-tdlib#19]
I'm stuck at trying to pin a message that I sent to a supergroup:
I got `Not enough rights to pin a message` when I call
```
	result, err := client.SendAndCatch(tdlib.UpdateData{
		"@type":                "pinChatMessage",
		"chat_id":              newChat.ID,
		"message_id":           msgID,
		"disable_notification": false,
	})
```
I tried the supergroupID but the error was `error! code: %!d(float64=6) msg: Message can't be pinned`

I had tried the client method `client.PinSupergroupMessage(mySuperGroup.SupergroupID, msgID, true)` which is of `@type` `pinSupergroupMessage` but it timed out

**Comment by Arman92** [comment]
Sorry for super late reply, are you sure you can pin it by the same account on a Telegram client?

**Comment by Arman92** [comment]
Can you give some updates on this issue?

**Comment by leonmak** [comment]
I don't recall since it's quite some time, but I think the bot has to be an admin
