### ISSUE TITLE
 client.RawUpdates

### ISSUE THREAD

**Issue by Psh777** [Arman92/go-tdlib#20]
client.RawUpdates undefined (type *tdlib.Client has no field or method RawUpdates)

**Comment by Arman92** [comment]
Please follow the examples.
You can't access client.rawUpdates directly, instead you should call GetRawUpdatesChannel to get the rawUpdates channel.

**Comment by danaki** [comment]
Got the same issue by just copying example from the README, I guess it should be updated though

**Comment by cybervagabond** [comment]
> Please follow the examples.
> You can't access client.rawUpdates directly, instead you should call GetRawUpdatesChannel to get the rawUpdates channel.

its example from readme that does not work :)

**Comment by McLayer** [comment]
Broken example is still there. Are you kidding? )
