### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MarlikAlmighty** [Arman92/go-tdlib#23]
go run main.go
# github.com/Arman92/go-tdlib
cgo-gcc-prolog: In function ‘_cgo_346a1d600dcf_Cfunc_td_set_log_file_path’:
cgo-gcc-prolog:144:2: warning: ‘td_set_log_file_path’ is deprecated [-Wdeprecated-declarations]
In file included from ../../pkg/mod/github.com/!arman92/go-tdlib@v0.0.0-20190517084650-5bbe270b752e/tdlib.go:11:0:
/usr/local/include/td/telegram/td_log.h:33:30: note: declared here
 TDJSON_DEPRECATED_EXPORT int td_set_log_file_path(const char *file_path);
                              ^~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function ‘_cgo_346a1d600dcf_Cfunc_td_set_log_verbosity_level’:
cgo-gcc-prolog:160:2: warning: ‘td_set_log_verbosity_level’ is deprecated [-Wdeprecated-declarations]
In file included from ../../pkg/mod/github.com/!arman92/go-tdlib@v0.0.0-20190517084650-5bbe270b752e/tdlib.go:11:0:
/usr/local/include/td/telegram/td_log.h:59:31: note: declared here
 TDJSON_DEPRECATED_EXPORT void td_set_log_verbosity_level(int new_verbosity_level);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Arman92** [comment]
Can you please put more details? Steps to reproduce?

**Comment by MarlikAlmighty** [comment]
```
package main

import (
	"fmt"

	"github.com/Arman92/go-tdlib"
)

func main() {
	tdlib.SetLogVerbosityLevel(1)
	tdlib.SetFilePath("./errors.txt")

	// Create new instance of client
	client := tdlib.NewClient(tdlib.Config{
		APIID:               "187786",
		APIHash:             "e782045df67ba48e441ccb105da8fc85",
		SystemLanguageCode:  "en",
		DeviceModel:         "Server",
		SystemVersion:       "1.0.0",
		ApplicationVersion:  "1.0.0",
		UseMessageDatabase:  true,
		UseFileDatabase:     true,
		UseChatInfoDatabase: true,
		UseTestDataCenter:   false,
		DatabaseDirectory:   "./tdlib-db",
		FileDirectory:       "./tdlib-files",
		IgnoreFileNames:     false,
	})

	for {
		currentState, _ := client.Authorize()
		if currentState.GetAuthorizationStateEnum() == tdlib.AuthorizationStateWaitPhoneNumberType {
			fmt.Print("Enter phone: ")
			var number string
			fmt.Scanln(&number)
			_, err := client.SendPhoneNumber(number)
			if err != nil {
				fmt.Printf("Error sending phone number: %v", err)
			}
		} else if currentState.GetAuthorizationStateEnum() == tdlib.AuthorizationStateWaitCodeType {
			fmt.Print("Enter code: ")
			var code string
			fmt.Scanln(&code)
			_, err := client.SendAuthCode(code)
			if err != nil {
				fmt.Printf("Error sending auth code : %v", err)
			}
		} else if currentState.GetAuthorizationStateEnum() == tdlib.AuthorizationStateWaitPasswordType {
			fmt.Print("Enter Password: ")
			var password string
			fmt.Scanln(&password)
			_, err := client.SendAuthPassword(password)
			if err != nil {
				fmt.Printf("Error sending auth password: %v", err)
			}
		} else if currentState.GetAuthorizationStateEnum() == tdlib.AuthorizationStateReadyType {
			fmt.Println("Authorization Ready! Let's rock")
			break
		}
	}

	// Main loop
	for update := range client.RawUpdates {
		// Show all updates
		fmt.Println(update.Data)
		fmt.Print("\n\n")
	}

}
```
go run main.go

**Comment by un000** [comment]
How did you solve this?

**Comment by Arman92** [comment]
OK, I haven't updated bindings to the latest tdlib, so it may be related to something getting deprecated.

Anyway did you manage to fix this?
