### ISSUE TITLE
td/telegram/tdjson_export.h: No such file

### ISSUE THREAD

**Issue by recoilme** [Arman92/go-tdlib#3]
When i try link tdlib as static lib i have this error in this line:
https://github.com/tdlib/td/blob/master/td/telegram/td_json_client.h#L50

Help me pls solve it...

**Comment by Arman92** [comment]
What's the error exactly?

**Comment by recoilme** [comment]
```
 go build
# github.com/recoilme/go-tdlib
In file included from ./tdlib.go:11:0:
/usr/local/include/td/telegram/td_log.h:15:39: fatal error: td/telegram/tdjson_export.h: No such file or directory
 #include "td/telegram/tdjson_export.h"
```
i dont see that file: td/telegram/tdjson_export.h

**Comment by recoilme** [comment]
Error was on build step with openssl lib
After fix (debian):
```
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/lib/ssl ..
```
i found this file
