### ISSUE TITLE
`capacity` argument is unused in unused in `GetRawUpdatesChannel()`

### ISSUE THREAD

**Issue by rutsky** [Arman92/go-tdlib#4]
`capacity` argument is unused in unused in `GetRawUpdatesChannel()`:

https://github.com/Arman92/go-tdlib/blob/b17628cff13f43511e86f45dec66cfaafff07df6/tdlib.go#L161-L164

Also `client.rawUpdates` is overwritten every time this function called, making result of previous call useless.

**Comment by Arman92** [comment]
Thank you @rutsky, I'll fix this as soon as possible.

**Comment by Arman92** [comment]
#5 Fixed
