### ISSUE TITLE
ViewMessages example

### ISSUE THREAD

**Issue by s3rj1k** [Arman92/go-tdlib#8]
Please add ViewMessages example that reads message from chat and marks this message as read.
Can't make this work :(

**Comment by s3rj1k** [comment]
@Arman92 ?

**Comment by Arman92** [comment]
Hi,
What have tried so far?

**Comment by s3rj1k** [comment]
Hi, used getChatList example

matched one chat by id, this works

for that char id I do:
```

			ok, err := client.OpenChat(chat.ID)
			spew.Dump(ok, err)

			msg, err := client.GetMessage(chat.ID, chat.LastReadInboxMessageID)
			spew.Dump(msg, err)

			ok, err = client.ViewMessages(chat.ID, []int64{chat.LastReadInboxMessageID}, true)
			spew.Dump(ok, err)

			ok, err = client.Close()
			spew.Dump(ok, err)
```

ViewMessages does not mark message as readed

**Comment by s3rj1k** [comment]
bump

**Comment by Arman92** [comment]
Sorry I took you too long, I've been busy as hell!

Well you are passing the LastReadInboxMessageID as second parameter to ViewMessages(), so you are asking to read the messages until LastReadInboxMessageID which is trivial.

Just replace it with 
```
chat.LastMessage.ID
```

That would be it.

**Comment by s3rj1k** [comment]
Actually there is more to it, you will have to open chat, do ViewMessages, close chat.
And pay attention that most of functions for getting messages return then in reverse chronological order
